/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf -T 
Files: scene.gltf [6.39KB] > C:\Users\Len\OneDrive\Desktop\Projects\threejs\r3f\public\models\trident\scene-transformed.glb [7.37KB] (-15%)
Author: kubAZ (https://sketchfab.com/az15042009)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/trident-7e844027c5cb4245b12baac0355b1ff8
Title: Trident
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
gsap.registerPlugin(ScrollTrigger);

export function Model(props: any) {
  const { nodes, materials } = useGLTF("/models/scene-transformed.glb");
  console.log(nodes, materials);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={(nodes.Cylinder_Material001_0 as THREE.Mesh).geometry}
        material={materials["Material.001"]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      />
    </group>
  );
}

useGLTF.preload("/models/scene-transformed.glb");
